### ISSUE TITLE
Parse empty file

### ISSUE THREAD

**Issue by durcak** [martijn/xsv#17]
Cannot parse empty excel with code:
```
workbook = Xsv::Workbook.open(@io, trim_empty_rows: true)
sheet = workbook.sheets[0]
sheet.parse_headers!

sheet.each_row do |row|
 row # => ["header1", "header2"], etc.
end
```

because of error:
```
NoMethodError: undefined method `zip' for nil:NilClass
from /Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/xsv-0.3.16/lib/xsv/sheet.rb:123:in `empty_row'
Caused by CSV::MalformedCSVError: Invalid byte sequence in UTF-8 in line 1.
from /Users/me/.rbenv/versions/2.7.1/lib/ruby/2.7.0/csv/parser.rb:346:in `rescue in parse'
Caused by CSV::Parser::InvalidEncoding: CSV::Parser::InvalidEncoding
from /Users/me/.rbenv/versions/2.7.1/lib/ruby/2.7.0/csv/parser.rb:229:in `read_chunk'
```

Thanks for help.

**Comment by martijn** [comment]
Thanks for reporting. I just pushed Xsv 0.3.17 with a fix!
